Repository arduino-libraries/ArduinoHttpClient, pull requests merged in 2024-03, with the labels that each got.

#173 Added Url parser
  .codespellrc
  examples/ParseURL/ParseURL.ino
  src/URLParser.h
  src/utility/URLParser/LICENSE
  src/utility/URLParser/README.md
  src/utility/URLParser/http_parser.c
  src/utility/URLParser/http_parser.h
Labels: type: enhancement, topic: code

#158 Add ability to set response wait time
  src/HttpClient.cpp
  src/HttpClient.h
Labels: type: enhancement, topic: code

#124 Added configurable WebSocket tx buffer size
  src/WebSocketClient.h
Labels: type: enhancement, topic: code

#90 ContentLength can go over 2 byte int
  src/HttpClient.cpp
  src/HttpClient.h
Labels: topic: code

#125 Reduce timeout from 1000ms to 100ms
  src/HttpClient.h
Labels: type: enhancement, topic: code

#161 Add 443 port for https requests
  src/HttpClient.cpp
  src/HttpClient.h
Labels: type: enhancement, topic: code

#152 Make sure to use HttpClient when upgrading the connection for websockets
  src/HttpClient.cpp
Labels: type: imperfection, topic: code
